import { ProductType } from '../types/products.types';

export const fakeProducts: ProductType[] = [
  {
    id: "1",
    title: "Wireless Headphones",
    price: "1999",
    quantity: 50,
    image: "https://picsum.photos/200?random=1",
  },
  {
    id: "2",
    title: "Gaming Mouse",
    price: "1499",
    quantity: 30,
    image: "https://picsum.photos/200?random=2",
  },
  {
    id: "3",
    title: "Mechanical Keyboard",
    price: "3499",
    quantity: 20,
    image: "https://picsum.photos/200?random=3",
  },
  {
    id: "4",
    title: "Smartphone Stand",
    price: "299",
    quantity: 100,
    image: "https://picsum.photos/200?random=4",
  },
  {
    id: "5",
    title: "USB-C Charger",
    price: "899",
    quantity: 40,
    image: "https://picsum.photos/200?random=5",
  },
  {
    id: "6",
    title: "Bluetooth Speaker",
    price: "2499",
    quantity: 35,
    image: "https://picsum.photos/200?random=6",
  },
  {
    id: "7",
    title: "LED Monitor 24 inch",
    price: "11999",
    quantity: 15,
    image: "https://picsum.photos/200?random=7",
  },
  {
    id: "8",
    title: "External Hard Drive 1TB",
    price: "4599",
    quantity: 25,
    image: "https://picsum.photos/200?random=8",
  },
  {
    id: "9",
    title: "Portable SSD 512GB",
    price: "6499",
    quantity: 10,
    image: "https://picsum.photos/200?random=9",
  },
  {
    id: "10",
    title: "Noise Cancelling Earbuds",
    price: "2999",
    quantity: 45,
    image: "https://picsum.photos/200?random=10",
  },
  {
    id: "11",
    title: "Smartwatch",
    price: "5499",
    quantity: 18,
    image: "https://picsum.photos/200?random=11",
  },
  {
    id: "12",
    title: "Fitness Tracker",
    price: "1799",
    quantity: 60,
    image: "https://picsum.photos/200?random=12",
  },
  {
    id: "13",
    title: "Laptop Backpack",
    price: "1399",
    quantity: 75,
    image: "https://picsum.photos/200?random=13",
  },
  {
    id: "14",
    title: "Wireless Mouse",
    price: "799",
    quantity: 55,
    image: "https://picsum.photos/200?random=14",
  },
  {
    id: "15",
    title: "Desk Lamp",
    price: "999",
    quantity: 35,
    image: "https://picsum.photos/200?random=15",
  },
  {
    id: "16",
    title: "Smartphone Tripod",
    price: "1299",
    quantity: 22,
    image: "https://picsum.photos/200?random=16",
  },
  {
    id: "17",
    title: "Wireless Charging Pad",
    price: "1499",
    quantity: 28,
    image: "https://picsum.photos/200?random=17",
  },
  {
    id: "18",
    title: "Gaming Chair",
    price: "15999",
    quantity: 12,
    image: "https://picsum.photos/200?random=18",
  },
  {
    id: "19",
    title: "Graphic Tablet",
    price: "6999",
    quantity: 8,
    image: "https://picsum.photos/200?random=19",
  },
  {
    id: "20",
    title: "Drone Camera",
    price: "24999",
    quantity: 5,
    image: "https://picsum.photos/200?random=20",
  },
];
